version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/transactions
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    networks:
      - postgres-compose-network
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=transactions
    ports:
      - "5432:5432"
    volumes:
      - ./database/setup:/docker-entrypoint-initdb.d
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge

